# Generated by Django 2.1.7 on 2019-04-10 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_test2model_test_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='test2model',
            name='test_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test3s', to='testapp.TestModel'),
        ),
    ]
