# Generated by Django 2.1.7 on 2019-04-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_test2model_test_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test3Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.TestModel')),
            ],
        ),
    ]
