# Generated by Django 2.1.7 on 2019-04-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_test3model'),
    ]

    operations = [
        migrations.AddField(
            model_name='test3model',
            name='text',
            field=models.CharField(blank=True, max_length=50, verbose_name='text'),
        ),
    ]
