# Generated by Django 2.1.7 on 2019-04-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_test3model_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='test3model',
            name='text_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='text 2'),
        ),
    ]
