# Generated by Django 2.1.7 on 2019-04-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_test3model_text_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test3model',
            name='text_2',
            field=models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=50, verbose_name='text 2'),
        ),
    ]
